"""empty message

Revision ID: 72f92e59300e
Revises: 90a13745a017
Create Date: 2023-07-23 09:31:27.599875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f92e59300e'
down_revision = '90a13745a017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.String(length=200), nullable=True))
        batch_op.drop_column('price_range')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_range', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_column('price')

    # ### end Alembic commands ###
