"""empty message

Revision ID: 5370218164aa
Revises: c8e7badfcc97
Create Date: 2023-08-06 16:42:40.972555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5370218164aa'
down_revision = 'c8e7badfcc97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Enum('Activity', 'Product', 'trip', name='myenum'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.Enum('Activity', 'Product', 'trip', name='myenum'),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###
