"""empty message

Revision ID: 392aa17aa6c9
Revises: 85dcffacd950
Create Date: 2023-08-06 17:12:00.151862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392aa17aa6c9'
down_revision = '85dcffacd950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Enum('activity', 'product', 'trip', name='myenum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
