"""empty message

Revision ID: 6928e579aa89
Revises: 721023873888
Create Date: 2023-08-17 11:27:57.837753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6928e579aa89'
down_revision = '721023873888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
