"""empty message

Revision ID: 6b4209270101
Revises: fc2588e4c640
Create Date: 2023-09-19 15:42:13.559257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b4209270101'
down_revision = 'fc2588e4c640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['verification_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('verification_token')

    # ### end Alembic commands ###
