"""empty message

Revision ID: 85dcffacd950
Revises: c8e7badfcc97
Create Date: 2023-08-06 17:11:08.084358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85dcffacd950'
down_revision = 'c8e7badfcc97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=250), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
