"""empty message

Revision ID: e9657c284db3
Revises: 
Create Date: 2023-08-19 13:16:36.227915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9657c284db3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('favourites', sa.ARRAY(sa.String(length=120)), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('location', sa.String(length=250), nullable=True),
    sa.Column('publishing_date', sa.String(length=10), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('price', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('activity', 'product', 'trip', name='myenum'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=False),
    sa.Column('rating', sa.String(length=50), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('review')
    op.drop_table('user')
    # ### end Alembic commands ###
