"""empty message

Revision ID: 6c726904facb
Revises: cdbcbd362758
Create Date: 2023-08-12 07:24:11.695553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c726904facb'
down_revision = 'cdbcbd362758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favourites', sa.ARRAY(sa.String(length=120)), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('favourites')

    # ### end Alembic commands ###
