"""empty message

Revision ID: cdbcbd362758
Revises: e0526672deca
Create Date: 2023-08-11 18:02:15.465248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdbcbd362758'
down_revision = 'e0526672deca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('location', sa.String(length=250), nullable=True),
    sa.Column('publishing_date', sa.String(length=10), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('price', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('activity', 'product', 'trip', name='myenum'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=False))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('username')

    op.drop_table('comment')
    op.drop_table('review')
    # ### end Alembic commands ###
