"""empty message

Revision ID: 610143a438b4
Revises: 6261e6f35101
Create Date: 2023-08-18 16:41:48.453485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610143a438b4'
down_revision = '6261e6f35101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('counter',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('counter',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
